# Generated by Django 4.1 on 2023-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switches",
            name="ts2",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
